#
# KOSE_顧客情報(個人情報あり)取得
#
---
in:
  type: ${kose_sys.conn}
  td_authentication_id: ${kose_sys.td_authentication_id}
  bucket: ${kose_sys.bucket}
  path_prefix: ${filename.customer_pii}
  decoders:
    - {type: gzip}
  parser:
    type: csv
    charset: UTF-8
    skip_header_lines: 1 # 顧客情報(個人情報あり)はヘッダー行あり
    delimiter: ","
    quote: '"'
    escape: '"'
    newline: CRLF
    allow_extra_columns: true # CSV項目の多寡は個人情報無しと同ファイルを参照するため許容する
    allow_optional_columns: true # CSV項目の多寡は個人情報無しと同ファイルを参照するため許容する
    columns:
      - {name: customer_code_hash, type: string}
      - {name: status, type: string}
      - {name: sex, type: string}
      - {name: birthday, type: string}
      - {name: lang, type: string}
      - {name: zip_code, type: string}
      - {name: country, type: string}
      - {name: state, type: string}
      - {name: currency_code, type: string}
      - {name: timezone, type: string}
      - {name: system_code, type: string}
      - {name: pris_merge_code_hash, type: string}
      - {name: pris_permissioncode, type: string}
      - {name: kpad_gatheringcode, type: string}
      - {name: kpad_shop_id, type: string}
      - {name: customer_code_2, type: string}
      - {name: customer_code_3, type: string}
      - {name: customer_code_4, type: string}
      - {name: customer_code_5, type: string}
      - {name: jillappcustomercode, type: string}
      - {name: mail_pc_hash, type: string}
      - {name: mail_mobile_hash, type: string}
      - {name: ablemail, type: string}
      - {name: sns_facebook, type: string}
      - {name: sns_twitter, type: string}
      - {name: sns_google, type: string}
      - {name: sns_yahoo, type: string}
      - {name: sns_line, type: string}
      - {name: linefriend, type: string}
      - {name: amazon, type: string}
      - {name: kpadclientclass, type: string}
      - {name: ecrank, type: string}
      - {name: calltime, type: string}
      - {name: clubkosedelete, type: string}
      - {name: clubkosedeletedate, type: string}
      - {name: systemcreatedate, type: string}
      - {name: systemupdatedate, type: string}
      - {name: affiliate, type: string}
      - {name: publishid, type: string}
      - {name: ip, type: string}
      - {name: browser, type: string}
      - {name: ecsight, type: string}
      - {name: mobileuid, type: string}
      - {name: guid, type: string}
      - {name: device, type: string}
      - {name: buytimes_shop, type: string}
      - {name: buytimes_ec, type: string}
      - {name: buytimes_ec_cancel, type: string}
      - {name: buytimes_ec_return, type: string}
      - {name: mailmagazine_jill, type: string}
      - {name: mailmagazine_flora, type: string}
      - {name: mailmagazine_maison, type: string}
      - {name: mailmagazine_maihada, type: string}
      - {name: mailmagazine_awake, type: string}
      - {name: mailmagazine_addiction, type: string}
      - {name: filecreatedate, type: string}
      - {name: periodical_active_flag, type: string}
      - {name: able_tel_flag, type: string}
      - {name: state_flag, type: string}
      - {name: mailmagazine_drphil, type: string}
      - {name: month_of_birth, type: string}
      - {name: memberscard_id, type: string}
      - {name: mailmagazine_mall, type: string}
      - {name: mailmagazine_sekkisei, type: string}
      - {name: customerrank_maihada, type: string}
      - {name: skin_troubles_maihada, type: string}
      - {name: mailmagazine_decorte, type: string}
      - {name: skin_troubles_decorte, type: string}
      - {name: skin_type_decorte, type: string}
      - {name: customerrank_decorte, type: string}
      - {name: koseid_createdate, type: string}
      - {name: city, type: string}
      - {name: address1, type: string}
      - {name: address2, type: string}
      - {name: tel, type: string}
      - {name: tel_memo, type: string}
      - {name: last_name, type: string}
      - {name: first_name, type: string}
      - {name: last_kana, type: string}
      - {name: first_kana, type: string}
      - {name: mail_pc, type: string}
      - {name: mail_mobile, type: string}
out:
  mode: append
filters:
  - type: rename
    columns:
      koseid_createdate: kose_id_createdate
  - type: column
    columns:
      - {name: customer_code_hash, type: string}
      - {name: status, type: string}
      - {name: sex, type: string}
      - {name: birthday, type: string}
      - {name: lang, type: string}
      - {name: zip_code, type: string}
      - {name: country, type: string}
      - {name: state, type: string}
      - {name: currency_code, type: string}
      - {name: timezone, type: string}
      - {name: system_code, type: string}
      - {name: pris_merge_code_hash, type: string}
      - {name: pris_permissioncode, type: string}
      - {name: kpad_gatheringcode, type: string}
      - {name: kpad_shop_id, type: string}
      - {name: customer_code_2, type: string}
      - {name: customer_code_3, type: string}
      - {name: customer_code_4, type: string}
      - {name: customer_code_5, type: string}
      - {name: jillappcustomercode, type: string}
      - {name: mail_pc_hash, type: string}
      - {name: mail_mobile_hash, type: string}
      - {name: ablemail, type: string}
      - {name: sns_facebook, type: string}
      - {name: sns_twitter, type: string}
      - {name: sns_google, type: string}
      - {name: sns_yahoo, type: string}
      - {name: sns_line, type: string}
      - {name: amazon, type: string}
      - {name: linefriend, type: string}
      - {name: kpadclientclass, type: string}
      - {name: ecrank, type: string}
      - {name: calltime, type: string}
      - {name: clubkosedelete, type: string}
      - {name: clubkosedeletedate, type: string}
      - {name: systemcreatedate, type: string}
      - {name: systemupdatedate, type: string}
      - {name: affiliate, type: string}
      - {name: publishid, type: string}
      - {name: ip, type: string}
      - {name: browser, type: string}
      - {name: ecsight, type: string}
      - {name: mobileuid, type: string}
      - {name: guid, type: string}
      - {name: device, type: string}
      - {name: buytimes_shop, type: string}
      - {name: buytimes_ec, type: string}
      - {name: buytimes_ec_cancel, type: string}
      - {name: buytimes_ec_return, type: string}
      - {name: mailmagazine_jill, type: string}
      - {name: mailmagazine_flora, type: string}
      - {name: mailmagazine_maison, type: string}
      - {name: mailmagazine_maihada, type: string}
      - {name: mailmagazine_awake, type: string}
      - {name: mailmagazine_addiction, type: string}
      - {name: filecreatedate, type: string}
      - {name: periodical_active_flag, type: string}
      - {name: able_tel_flag, type: string}
      - {name: state_flag, type: string}
      - {name: mailmagazine_drphil, type: string}
      - {name: month_of_birth, type: string}
      - {name: memberscard_id, type: string}
      - {name: mailmagazine_mall, type: string}
      - {name: mailmagazine_sekkisei, type: string}
      - {name: customerrank_maihada, type: string}
      - {name: skin_troubles_maihada, type: string}
      - {name: mailmagazine_decorte, type: string}
      - {name: skin_troubles_decorte, type: string}
      - {name: skin_type_decorte, type: string}
      - {name: customerrank_decorte, type: string}
      - {name: kose_id_createdate, type: string}
      - {name: city, type: string}
      - {name: address1, type: string}
      - {name: address2, type: string}
      - {name: tel, type: string}
      - {name: tel_memo, type: string}
      - {name: last_name, type: string}
      - {name: first_name, type: string}
      - {name: last_kana, type: string}
      - {name: first_kana, type: string}
      - {name: mail_pc, type: string}
      - {name: mail_mobile, type: string}
  - type: add_time
    to_column: {name: time}
    from_value: {value: ${moment(session_time).unix()}, unix_timestamp_unit: sec}
