in:
  type: ${adebis.conn}
  td_authentication_id: ${adebis.td_authentication_id}
  user_directory_is_root: true
  timeout: 600
  path_prefix: ${adebis.path_prefix}
  path_match_pattern: adebis_provision_10035030_conversions
  decoders:
    - {type: gzip}
  parser:
    type: json
    columns:
      - {name: conversionId, type: long}
      - {name: conversionTitle, type: string}
      - {name: pageId, type: string}
      - {name: rank, type: long}
      - {name: conversionTypeId, type: long}
out:
  mode: replace
filters:
  - type: rename
    columns:
      conversionId: conversionid
      conversionTitle: conversiontitle
      pageId: pageid
      rank: rank
      conversionTypeId: conversiontypeid
  - type: column
    columns:
      - {name: conversionid, type: long}
      - {name: conversiontitle, type: string}
      - {name: pageid, type: string}
      - {name: rank, type: long}
      - {name: conversiontypeid, type: long}
  - type: add_time
    to_column: {name: time}
    from_value: {value: ${moment(session_time).unix()}, unix_timestamp_unit: sec}
