-- @TD engine_version: 350
select 
	date, --日付（基準日）
	year_month, --年月
	system_cd, --利用システムコード
	topic, --トピック/施策
	brand, --ブランド
	target_sales_amount, --目標売上
	total_target_sales_amount, --目標売上（累計）
	out_sales_amount, --出荷売上
	out_sales_amount_ec, --出荷売上自社EC
	out_sales_amount_ex, --出荷売上外販
	total_out_sales_amount, --出荷売上（累計）
	lm_out_sales_amount, --出荷前月売上
	total_lm_out_sales_amount, --出荷前月売上（累計）
	ly_out_sales_amount, --出荷前年売上
	total_ly_out_sales_amount, --出荷前年売上（累計）
	price_result, --受注売上
	total_price_result, --受注売上（累計）
	lm_price_result, --受注前月売上
	total_lm_price_result, --受注前月売上（累計）
	ly_price_result, --受注前年売上
	total_ly_price_result, --受注前年売上（累計）
	price_result_tar_r, --受注売上（目標比）
	price_result_lm_r, --受注売上（前月比）
	price_result_ly_r, --受注売上（前年比）
	total_lo_price, --残出荷額（累計）
	unique_user, --UU
	page_view, --PV
	session_cnt, --セッション数
	purchases_cnt, --購入件数
	purchases_r, --購入率
	avarage_order_unit_price, --平均注文単価
	new_member_cnt, --新規会員数
	new_member_cnt_r, --新規会員登録率
	buyer_cnt, --購入者数
	ex_buyer_r, --既存購入者率
	new_buyer_r, --新規購入者率
 	repeat_r_30, --リピート率30
 	repeat_r_60, --リピート率60
 	repeat_r_90, --リピート率90
 	repeat_r_180 --リピート率180 
from tmp_bi_sales_detail