SELECT
	IF(order_no = '', null, order_no) AS ORDER_NO,
	IF(cst_id = '', null, cst_id) AS CST_ID,
	IF(order_date = '', null, order_date) AS ORDER_DATE,
	IF(ship_del_date = '', null, ship_del_date) AS SHIP_DEL_DATE,
	IF(cm_cd = '', null, cm_cd) AS CM_CD,
	IF(cm_nm = '', null, cm_nm) AS CM_NM,
	sn_price AS SN_PRICE,
	si_price AS SI_PRICE,
	order_qty AS ORDER_QTY,
	IF(cancel_kb = '', null, cancel_kb) AS CANCEL_KB,
	IF(return_kb = '', null, return_kb) AS RETURN_KB,
	IF(sales_kb = '', null, sales_kb) AS SALES_KB,
	IF(sp_cd = '', null, sp_cd) AS SP_CD,
	IF(first_buy_time = '', null, first_buy_time) AS FIRST_BUY_TIME,
	IF(last_buy_time = '', null, last_buy_time) AS LAST_BUY_TIME,
	IF(input_div = '', null, input_div) AS INPUT_DIV,
	IF(add_point = '', null, add_point) AS ADD_POINT,
	IF(media_cd = '', null, media_cd) AS MEDIA_CD,
	IF(pay_method = '', null, pay_method) AS PAY_METHOD,
	buy_qty AS BUY_QTY,
	buy_nprice AS BUY_NPRICE,
	buy_price AS BUY_PRICE,
	IF(event_date = '', null, event_date) AS EVENT_DATE,
	selling_price_ex_vat AS SELLING_PRICE_EX_VAT,
	selling_price_in_vat AS SELLING_PRICE_IN_VAT,
	IF(trial_vat = '', null, trial_vat) AS TRIAL_VAT,
	IF(brand = '', null, brand) AS BRAND
FROM
	probance_data_order
EXCEPT
SELECT
	IF(order_no = '', null, order_no) AS ORDER_NO,
	IF(cst_id = '', null, cst_id) AS CST_ID,
	IF(order_date = '', null, order_date) AS ORDER_DATE,
	IF(ship_del_date = '', null, ship_del_date) AS SHIP_DEL_DATE,
	IF(cm_cd = '', null, cm_cd) AS CM_CD,
	IF(cm_nm = '', null, cm_nm) AS CM_NM,
	sn_price AS SN_PRICE,
	si_price AS SI_PRICE,
	order_qty AS ORDER_QTY,
	IF(cancel_kb = '', null, cancel_kb) AS CANCEL_KB,
	IF(return_kb = '', null, return_kb) AS RETURN_KB,
	IF(sales_kb = '', null, sales_kb) AS SALES_KB,
	IF(sp_cd = '', null, sp_cd) AS SP_CD,
	IF(first_buy_time = '', null, first_buy_time) AS FIRST_BUY_TIME,
	IF(last_buy_time = '', null, last_buy_time) AS LAST_BUY_TIME,
	IF(input_div = '', null, input_div) AS INPUT_DIV,
	IF(add_point = '', null, add_point) AS ADD_POINT,
	IF(media_cd = '', null, media_cd) AS MEDIA_CD,
	IF(pay_method = '', null, pay_method) AS PAY_METHOD,
	buy_qty AS BUY_QTY,
	buy_nprice AS BUY_NPRICE,
	buy_price AS BUY_PRICE,
	IF(event_date = '', null, event_date) AS EVENT_DATE,
	selling_price_ex_vat AS SELLING_PRICE_EX_VAT,
	selling_price_in_vat AS SELLING_PRICE_IN_VAT,
	IF(trial_vat = '', null, trial_vat) AS TRIAL_VAT,
	IF(brand = '', null, brand) AS BRAND
FROM
	kosedmp_prd_secure.probance_previous_data_order