name: Secretlint
on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
env:
  CI: true
jobs:
  secretlint:
    name: "Secretlint"
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PULL_ACCESS_TOKEN }}
      - name: checkout
        uses: actions/checkout@v4
      - name: lint with secretlint on docker
        run: |
           docker run -v "$(pwd)":"$(pwd)" \
             -w "$(pwd)" \
             --rm \
             secretlint/secretlint:latest secretlint \
             --secretlintrc .github/workflows/.secretlintrc.json \
             --secretlintignore .github/workflows/.secretlintignore \
             --format @secretlint/secretlint-formatter-sarif \
             --output results.sarif \
             "**/*"
      - name: upload sarif file
        if: ${{ always() }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'results.sarif'
          category: 'secretlint'
